### ISSUE TITLE
Custom markers

### ISSUE THREAD

**Issue by Brawl345** [pl3xgaming/Pl3xMap#101]
Is it possible to add custom markers to the map?

**Comment by granny** [comment]
Sure, through an addon. https://github.com/SentixDev/Pl3xMap-Marker was just recently added to the [ADDONS_INTEGRATIONS.md](https://github.com/pl3xgaming/Pl3xMap/blob/master/ADDONS_INTEGRATIONS.md) page that should do what you want.
