### ISSUE TITLE
Server Crashing Issue (Memory leak/issue with Pl3xmap?)

### ISSUE THREAD

**Issue by skw359** [pl3xgaming/Pl3xMap#105]
When using `/pl3xmap radiusrender <insert any number above ~5k here, 10K works best>` and canceling the task mid-render, it will proceed to extremely rapidly crash the server due to the lack of memory and GC not being able to do anything. I was able to take a spark heapsummary and here is the output: https://spark.lucko.me/m9p63YZVWH (I have 14 GB of memory allocated, 13.47 being used?)

The server will begin to drastically slow down within seconds and crash. Console will look something like this: https://pastebin.com/G5cVNdHh (you can tell it's extremely crashy, super fun) 

I have taken a heapdump, however, I'm not sure if I should share it here for security reasons. I can share an output of analysis of it though

Please ask for more details if necessary :D

**Comment by Strahilchu** [comment]
Yeah pl3xmap is horrible for performance, eats up all the ram and the server can't keep up... just terrible.

**Comment by theomega24** [comment]
@Strahilchu I would provide information of your own instead of just complaining on the public issue tracker

**Comment by Strahilchu** [comment]
> @Strahilchu I would provide information of your own instead of just complaining on the public issue tracker

Okay here
Pl3xMap lagged out and crashed an R9-5950x CPU , 10GB ram server within 30 seconds with no players online.

**Comment by Strahilchu** [comment]
This happens to me with Pl3xMap but Dynmap never uses up much ram at all or CPU to crash, so I'm surprised to see that Pl3xMap was able to bring down my 20gb ram server with a 5950x cpu

**Comment by TheHappyHopper** [comment]
I had this same issue, but it seems to not be a memory leak issue, but rather a problem with pl3xmap's ram economy itself, i only managed to get it working with a hacky workaround to have my server auto restart every 20 minutes until the render's done, after that pl3xmap runs fine with no issues at all. The only problem with the current system is that it needs a way to not fill up the ram to the point that the server crashes

**Comment by BillyGalbreath** [comment]
See comment on bullet point 3 here https://github.com/pl3xgaming/Pl3xMap/issues/111#issuecomment-977191474

**Comment by TheHappyHopper** [comment]
The issue with that is that in using the ram it has available it fills up the memory completely and then eventually runs out, i havent found a way to make this work as intended yet

**Comment by BillyGalbreath** [comment]
> There is no issue here, this is simply how things work which is largely misunderstood by server owners.

This is a conversation better suited for Discord, honestly. It's a common misconception many server owners seem to have about how RAM works, especially inside a JVM.
