### ISSUE TITLE
[Feature Request] Add an option to skip rendering blocks above certain y-level

### ISSUE THREAD

**Issue by YouHaveTrouble** [pl3xgaming/Pl3xMap#12]
I'd like to suggest an option to set the height level from which to check for the blocks, as in my case I have a decorative glass structure above the actual spawn city and an option to skip like 60 blocks from the top would be useful.

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Pl3xMap/commit/3a95cefe980ec330eb4f472b77d62392db8845db
