### ISSUE TITLE
Requested Addons

### ISSUE THREAD

**Issue by BillyGalbreath** [pl3xgaming/Pl3xMap#18]
This is a list of addons that have been requested by the community. Unfortunately I do not personally have enough time (or sometimes knowledge about the requested plugin) to make and support them all. So I am compiling a list here in hopes someone else would like to take on the challenge of one (or more). ^_^

* ~~Banners - named banner markers~~ - claimed by [granny](https://github.com/granny/Pl3xMap-Banners)
* ~~[GriefDefender](https://www.spigotmc.org/resources/griefdefender.68900/) - region markers~~ - https://github.com/bloodmc/GDHooks
* [GWarp](https://www.spigotmc.org/resources/gwarp.56824/) - warp marker icons
* [Quests](https://www.spigotmc.org/resources/quests.3711/) - question objective region markers
* ~~[Residence](https://www.spigotmc.org/resources/residence.11480/) - region markers~~ - integrated
* [KingdomsX](https://www.spigotmc.org/resources/kingdomsx.77670/) - region markers
* [Citizens](https://www.spigotmc.org/resources/citizens.13811/) - NPC player icons
* [PlotSquared](https://www.spigotmc.org/resources/plotsquared.1177/) - region markers
* `/map hidetemp <Player> <Time>` command

Here are some basic addons I've already made, but if someone would like to take it over I'd be happy to hand it over.

* [ClaimChunk](https://github.com/pl3xgaming/Pl3xMap-ClaimChunk) - region markers
* [DeathSpot](https://github.com/pl3xgaming/Pl3xMap-DeathSpot) - death markers
* [Essentials](https://github.com/pl3xgaming/Pl3xMap-Essentials) - hide vanished players, warp marker icons
* [GriefPrevention](https://github.com/pl3xgaming/Pl3xMap-GriefPrevention) - region markers
* [Mobs](https://github.com/pl3xgaming/Pl3xMap-Mobs) - mob entity markers
* [Signs](https://github.com/pl3xgaming/Pl3xMap-Signs) - sign marker icons
* ~~SuperVanish - hide vanished players~~ (claimed by [notOM3GA](https://github.com/notOM3GA/Pl3xMap-SuperVanish))
* ~~Towny - region markers~~ (claimed by [silverwolfg11](https://github.com/silverwolfg11/Pl3xMap-Towny))
* [WorldGuard](https://github.com/pl3xgaming/Pl3xMap-WorldGuard) - region markers

You can talk to me in discord about any of these, or any others not listed.

**Comment by DoctaEnkoda** [comment]
I am create first commit for Residence here : https://github.com/systeme-cardinal/Pl3xMap-Residence/tree/dev/1.0

**Comment by Envel-Nikita-Gutsenkov** [comment]
add UltimateClaims please https://github.com/songoda/UltimateClaims

**Comment by emielderckx** [comment]
add some kind of structure markers: https://github.com/KovuTheHusky/dynmap-structures

**Comment by AAigars** [comment]
I have created a addon to support VanishNoPacket: https://github.com/AAigars/Pl3xMap-VanishNoPacket

**Comment by BillyGalbreath** [comment]
> I have created a addon to support VanishNoPacket: https://github.com/AAigars/Pl3xMap-VanishNoPacket

\o/ Sweet deal! ^_^

This ticket is for things that _haven't_ been created yet. A kind of "wish list", per se.

You'll want to PR you project to the https://github.com/pl3xgaming/Pl3xMap/blob/master/ADDONS_INTEGRATIONS.md file so everyone can find it ;)

**Comment by EdyTheCow** [comment]
Any chance of adding support for PlotSquared plugin? Basically just displaying basic plot information when clicked.

**Comment by ElFrod0** [comment]
Residence plugin added direct support for Pl3xmap - https://github.com/Zrips/Residence/commit/7ceef87e90215cd74e3d453af90206e35ae23d8f

**Comment by ahdg6** [comment]
GriefDefender has implemented it in GDHooks:https://github.com/bloodmc/GDHooks

**Comment by Encode42** [comment]
PR these to https://github.com/pl3xgaming/Pl3xMap/blob/master/ADDONS_INTEGRATIONS.md!

**Comment by Encode42** [comment]
@mesl Already exists, check [ADDONS_INTEGRATIONS.md](https://github.com/pl3xgaming/Pl3xMap/blob/master/ADDONS_INTEGRATIONS.md) (SuperVanish and PremiumVanish have the same API)
