### ISSUE TITLE
(Suggestion) Add Skinrestorer support

### ISSUE THREAD

**Issue by LichLord91** [pl3xgaming/Pl3xMap#20]
Skin Restorer :

- [Spigot Store](https://www.spigotmc.org/resources/skinsrestorer.2124)
- [Github Link](https://github.com/SkinsRestorer/SkinsRestorerX)
- [Api Mention](https://github.com/SkinsRestorer/SkinsRestorerX/wiki/SkinsRestorerAPI)
- [Issue I commented on for future improvements:](https://github.com/SkinsRestorer/SkinsRestorerX/issues/182)

Summary

This feature would be great to show the players head avatars for on the fly skin swapping , Offline users, and GeyserMC players. This is supported in Dynmap and would be a great feature to add to Pl3xmap (IMO).

We had a brief discussion about it in the discord. 

[Original Message](https://discord.com/channels/685683385313919172/798354811669446676/810610068029571093)
![image](https://user-images.githubusercontent.com/8435580/108058149-729eef80-7008-11eb-8bd3-9db14ca9930b.png)

It seems as they do for SkinRestorer specifically.

Camotoy also threw in some $.02 about how it could possibly done.

[1st comment](https://discord.com/channels/685683385313919172/798354811669446676/810613799308099644)

[2nd comment](https://discord.com/channels/685683385313919172/798354811669446676/810620806937837569)

These seem to be the configuration options that would help support this in dynmap's configuration.txt file:

```
# custom-colors-support: if true, Custom Colors in texture packs is enabled (default)
custom-colors-support: true

# Control loading of player faces (if set to false, skins are never fetched)
fetchskins: true

# Control updating of player faces, once loaded (if faces are being managed by other apps or manually)
refreshskins: true

# Customize URL used for fetching player skins (%player% is macro for name)
skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png"

# Enable skins via SkinsRestorer plugin instead of internal legacy implementation (disabled by default)
skinsrestorer-integration: true

```

Dynmap's original commit for Skinrestorer (i think) 

`https://github.com/webbukkit/dynmap/commit/578c66e2fe6de9e83f9e9ad1b8508a1def97aae1`

P.S. Thanks for taking the time to read BIlly , appreciate the work that you're doing. <3

**Comment by BillyGalbreath** [comment]
I already knew how to do this without using their API. I was just reluctant on doing so because it opens up the possibility for cracked/offline servers to use. I do not condone the use of piracy in any way shape or form, and try to actively block it where I can.

With that said, I went ahead and made a small addon because Geyser is indeed a valid use-case.

**Comment by LichLord91** [comment]
Hey Billy, installed and its working TYSM.  

1 small issue and 1 requests .

1.  looks like the image is set to save at 8x8 instead of 16x16 as I think you intended.  So it comes out really smol.

2. Is there a way to add a boolean option in the config  to add the player avatar with the helm layer as well?  

I believe Dynmap does it here in their implementation to grab the layers of the skin

https://github.com/webbukkit/dynmap/blob/578c66e2fe6de9e83f9e9ad1b8508a1def97aae1/DynmapCore/src/main/java/org/dynmap/PlayerFaces.java#L101

![image](https://user-images.githubusercontent.com/8435580/108139665-643aed00-7075-11eb-8232-b4d83df13cba.png)
