### ISSUE TITLE
Suggestion: Permission to only allow players to hide/show themselves

### ISSUE THREAD

**Issue by kev2k2de** [pl3xgaming/Pl3xMap#21]
We would like to give every player the ability to hide himself on the map, but currently, any player with the show/hide permission can use the command on all players.

**Comment by Folas1337** [comment]
Was about to suggest the same thing. It's the only thing preventing me from using it right now :/

**Comment by Folas1337** [comment]
May I bring this back to people's attention with a comment?
I'm assuming it's not that complicated to add and I'd really love to see this already 😐 

Big thanks in advance ❤️
