### ISSUE TITLE
Render command fails with 0 region files found

### ISSUE THREAD

**Issue by Encode42** [pl3xgaming/Pl3xMap#23]
The `map fullrender` command always fails due to 0 region files found. Doesn't matter if a world is specified or the command is ran in the console.

- Running on a shared host with Pterodactyl Panel 1.X (RetroNode)
- Permissions are correct (read/write)
- World and region files exist
- Happens whether or not a world is specified

Running Java 11 on Purpur 1.16.5.

**Comment by Rokkar** [comment]
I have this issue as well. same message.

Radius render works fine.

**Comment by koutsie** [comment]
+1 for the issue (happened when trying to render nether): ran the command as an user and it worked?
