### ISSUE TITLE
Addon request for TownyAdvanced

### ISSUE THREAD

**Issue by ofunny** [pl3xgaming/Pl3xMap#24]
Hi,
not sure if it is the right place, if not, just delete it.
But it would be cool if your plugin would support Towny (https://www.spigotmc.org/resources/towny-advanced.72694/).
Just showing the towns and a label with basic town infos like the Dynmap integration https://github.com/TownyAdvanced/Dynmap-Towny would be more than enough. 
Thanks

**Comment by BillyGalbreath** [comment]
See #18
