### ISSUE TITLE
Error when starting with the plugin for the first time

### ISSUE THREAD

**Issue by CocoTheOwner** [pl3xgaming/Pl3xMap#26]
Good day, I downloaded the plugin and ran it, noticing the error that pointed to this issue report.
I updated my java version, only to find it doing the same thing.

Here is a snippet of my log (the very first lines) containing java information:
`java -Xms10G -Xmx10G -jar paper165.jar nogui
System Info: Java 11 (Java HotSpot(TM) 64-Bit Server VM 11.0.10+8-LTS-162) Host: Windows 10 10.0 (amd64)`

As you can see later in the log I am running the 124th BETA build on the latest 1.16.5 paper.

Full log: https://pastebin.com/y5mD7BtW

This is on a fresh 1.16.5 paper server (which I created after I ran it on a server with a bunch of other plugins to make sure it wasn't some kind of incompatibility).

Let me know if there's more information you need. I'd love to be able to use this software!

Requested to be moved from issue 4

**Comment by C0ffeL0Ve** [comment]
i was waiting this post to get a response from the owners but it seems like this post is never going to get a response.

go to this page: https://www.openlogic.com/openjdk-downloads
in java sections select java 11 and download the openjdk 11,0,9,1+1

for me it worked, good luck.
