### ISSUE TITLE
Suggestion: Option to only accept traffic from specific IP-Address

### ISSUE THREAD

**Issue by motz0815** [pl3xgaming/Pl3xMap#28]
So,
I have an apache-proxy in front of the internal webserver of the plugin.
That's because the apache-webserver is running on a different server than the one that's running the minecraftserver/pl3xmap.
The only thing that the proxy is doing is a ssl-certificate + port 80/443.
I cannot host the apache on the same server as the minecraftserver because it is hosted by a serverhoster, and I only have 2 ports available there, the gameport + 1 addition one.

The suggestion:
Add an option in the config to only listen for a single (maybe even multiple) ip-addresses that have the right to connect to the webserver.

Thanks in advance for your replies,
motz

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Pl3xMap/wiki/Default-config.yml

![image](https://user-images.githubusercontent.com/332527/110354366-b11f3d00-7ffd-11eb-8daa-907bbd596aff.png)

**Comment by motz0815** [comment]
Uhm, I don't know, maybe I'm using that wrongly,
but if I type the ip-address, which the proxy will come from,
I get a Java BindException in my server-console.
Sorry if I'm bothering you with this :D

**Comment by BillyGalbreath** [comment]
Oh, I read the question wrong the first time.

This is not something you want to handle on an application level. You will want to setup a new rule in your firewall to only allow connections from the proxy server's ip address.
