### ISSUE TITLE
Suggestion: Option to hide underground players + players sneaking.

### ISSUE THREAD

**Issue by Agaloth** [pl3xgaming/Pl3xMap#29]
Basically, a config line which will allow you to toggle hiding players underground (when they mine, etc...) then another line that makes so players using shift to sneak won't be seen on the map.

**Comment by Agaloth** [comment]
Closed it accidentally, any updates on when this could potentially be added?

**Comment by Agaloth** [comment]
Any news to get this in the actual pl3xmap (1.16.5 and 1.17.1?)

**Comment by theomega24** [comment]
Because of how the rolling release works, it definitely won't be coming to 1.16.5. And probably not 1.17 (view #51)
