### ISSUE TITLE
My server goes up to 800% CPU usage w/ a Ryzen 3600 |  net.pl3x.map.plugin.task.UpdateMarkers.run error

### ISSUE THREAD

**Issue by yashendra2797** [pl3xgaming/Pl3xMap#30]
I have a dedicated machine. Ryzen 3600, 64 GB ram, you know the works. One of my servers, the only one running Pl3xmap, has in 2 days gone up to 800% CPU usage while normally its barely in the two digit percent.

March 11th: https://mclo.gs/SylqpXP (Line 781)
March 13th (today): https://mclo.gs/ArUHrby

Both days its the same error in console:` net.pl3x.map.plugin.task.UpdateMarkers.run(UpdateMarkers.java:86) `

I am running these expansions: mobs, skins, essentials, signs.

Please let me know if there is anything else I can do to troubleshoot this. Thanks!

**Comment by BillyGalbreath** [comment]
As states in Discord:

```
the log you posted today has 235 watchdog thread dumps from the server lagging. 5 of those contain pl3xmap in the dump.

the log you posted from 2 days ago has 436 watchdog thread dumps from the server lagging. 12 of those contain pl3xmap in the dump.

I'm pretty sure something not related to pl3xmap is causing lag for everything on your system
i also notice the log from today is showing a live backup while the server is running. this is generally advised against. you should really take your server offline to back it up to prevent the process from lagging the rest of the server, and worse things such as concurrent i/o errors which could corrupt your backup or your live data (or both)
```
