### ISSUE TITLE
Health error

### ISSUE THREAD

**Issue by 100petr** [pl3xgaming/Pl3xMap#32]
The browser console is spamming me with this error, I think it's because one of the players has a health boost or something
GET http://82.208.17.82:29368/images/health/28.png 404 (Not Found)
28.png:1 GET http://82.208.17.82:29368/images/health/28.png 404 (Not Found)
I have other HP pictures.
![image](https://user-images.githubusercontent.com/29830635/111157543-48a10480-8597-11eb-90f6-9d8f6d35f5c2.png)

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/111766975-71324280-88a6-11eb-86fc-993512d3a26b.png)
When I added 28 HP the image is again missing 24, 26. It would work better than having a picture for everything.

**Comment by pop4959** [comment]
Having an image for every possible health value is probably not ideal, definitely better if Pl3xmap just stored 2 images - one for half a heart and one for a full heart, and dynamically displayed the health. At high enough health values it may not be feasible to display the images though and maybe just print a number as Minecraft's in-game scoreboards do at a certain point.
