### ISSUE TITLE
Suggestion: Configurable player list sort method

### ISSUE THREAD

**Issue by itswilven** [pl3xgaming/Pl3xMap#42]
At the moment, the player list in the right side panel lists players based on their connection to the server, or if they changed dimensions. Would it be possible to sort this data after it is updated, so that it is optionally in alphabetical order?

For larger player count servers, this would make it a lot easier to find specific users online.

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Pl3xMap/commit/e1fe1f30ffa4354778cb7163030992dd93363482
