### ISSUE TITLE
Add ability for multiple renderers

### ISSUE THREAD

**Issue by BillyGalbreath** [pl3xgaming/Pl3xMap#44]
Right now there's only 1 renderer, the surface. I think it would be nice to add the ability to create other renderers via api for add-ons.

The plugin can ship with an extra renderer that renders only biomes (no heightmap, no blocks. just biomes. screenshot of possible design attached). Others could then be supplied by add-ons.

This would require a major change in the configuration structure, starting with the ability to add a world multiple times (in case multiple renderers are desired).

More thought needs to be put into this idea before work begins.

![image](https://user-images.githubusercontent.com/332527/116806953-00618580-aaf6-11eb-8392-00e339031f70.png)

**Comment by craftish37** [comment]
To show the biomes, maybe just use overlays who are activables/unactivables for webusers like towns or claims to compare with some addons 👀
