### ISSUE TITLE
Hiding through the pl3xmap api doesn't apply to the playercount

### ISSUE THREAD

**Issue by Roan-V** [pl3xgaming/Pl3xMap#62]
Hiding through the pl3xmap api doesn't apply to the playercount in the sidebar.
With only one hidden player online the playerlist will be empty but still show 1/x players online. Instead of 0/x.

https://discord.com/channels/838127837667131433/838128154764902411/860494644232060979

**Comment by granny** [comment]
Just tested this with the https://github.com/theomega24/Pl3xMap-SuperVanish addon and the player count updates correctly. If you can share steps to reproduce then I'll reopen this issue.
