### ISSUE TITLE
Unable to use world names including spaces

### ISSUE THREAD

**Issue by Til-Weimann** [pl3xgaming/Pl3xMap#72]
Hey,
My world name unfortunately contains a space.
Is there a way to still use this world in commands?
If you, can you implement one? Something like 'wor ld', for example?
Thanks

**Comment by Isabello** [comment]
I had the same issue. The workaround we used was renaming to use _ instead of space. Not quite ideal but no form or '', "", etc worked.

**Comment by notOM3GA** [comment]
World names with spaces are not supposed to exist. Mojang & Bukkit do not work properly with them. The correct naming scheme is lower_snake_case
