### ISSUE TITLE
Crash 1.17.1

### ISSUE THREAD

**Issue by arturek1666** [pl3xgaming/Pl3xMap#77]
I am getting this crash after updating my engine:
SSspigot 1.17.1 papermc and tuinity fork
Plugin version: BETA-159
How this error show, Updated engine after that this message started to show up, and server shut downs each time

> [01:05:20] [Server thread/ERROR]: Encountered an unexpected exception
> java.lang.NoClassDefFoundError: net/pl3x/map/plugin/lib/cloud/commandframework/arguments/StandardCommandSyntaxFormatter$FormattingInstance
> 	at net.pl3x.map.plugin.lib.cloud.commandframework.arguments.StandardCommandSyntaxFormatter.createInstance(StandardCommandSyntaxFormatter.java:126) ~[Pl3xMap-1.0.0-BETA-159.jar:?]
> 	at net.pl3x.map.plugin.lib.cloud.commandframework.arguments.StandardCommandSyntaxFormatter.apply(StandardCommandSyntaxFormatter.java:57) ~[Pl3xMap-1.0.0-BETA-159.jar:?]
> 	at net.pl3x.map.plugin.lib.cloud.commandframework.bukkit.BukkitCommand.getUsage(BukkitCommand.java:198) ~[Pl3xMap-1.0.0-BETA-159.jar:?]
> 	at org.bukkit.help.GenericCommandHelpTopic.<init>(GenericCommandHelpTopic.java:50) ~[ssspigot29194576346619863254.jar:SSSpigot2-1.17.1-20210817-85ace39]
> 	at org.bukkit.craftbukkit.v1_17_R1.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:135) ~[ssspigot29194576346619863254.jar:SSSpigot2-1.17.1-20210817-85ace39]
> 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:457) ~[ssspigot29194576346619863254.jar:SSSpigot2-1.17.1-20210817-85ace39]
> 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:726) ~[ssspigot29194576346619863254.jar:SSSpigot2-1.17.1-20210817-85ace39]
> 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:329) ~[ssspigot29194576346619863254.jar:SSSpigot2-1.17.1-20210817-85ace39]
> 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1219) ~[ssspigot29194576346619863254.jar:SSSpigot2-1.17.1-20210817-85ace39]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[ssspigot29194576346619863254.jar:SSSpigot2-1.17.1-20210817-85ace39]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]

Crash log:
https://gist.github.com/arturek1666/ffe6aefc35cb169b9985bd41f2f3dfe3

If this has something with engine instead I will contact them however I had to try here first maybe any idea :)

**Comment by BillyGalbreath** [comment]
We don't support SSSpigot, or any other yatopia-type or closed source fork.
