### ISSUE TITLE
Reprint and share plugin.

### ISSUE THREAD

**Issue by DreamVoid** [pl3xgaming/Pl3xMap#80]
Can I reprint Pl3xMap to MCBBS(A Minecraft forum in China, which can also release original or reprinted plugin)? I believe that server owners from China will like your plugin. Also, I will mark you as the author, link to your Github and never profit from them. I hope you can agree to my request.
Best regard <3

**Comment by Xarius86** [comment]
Pl3xMap is open source and released under the very permissive MIT license. https://github.com/pl3xgaming/Pl3xMap/blob/master/LICENSE

**Comment by DreamVoid** [comment]
> Pl3xMap is open source and released under the very permissive MIT license. https://github.com/pl3xgaming/Pl3xMap/blob/master/LICENSE

A rule of MCBBS is that no matter whether the plugin is open source or what the open source agreement is, the author's explicit consent is required.

**Comment by Xarius86** [comment]
I see. I'm unfamiliar with MCBBS or how it operates. Seeing as the license already permits what you are asking, I doubt you'll get any objections from Billy.
