### ISSUE TITLE
Pl3x not rendering old chunks

### ISSUE THREAD

**Issue by jaknz** [pl3xgaming/Pl3xMap#81]
I loaded an old world with latest Paper on MC 1.17.1, along with latest Pl3xmap. The chunks I actively visit have been updated, but I can't get the map to render anything else. I ran chunky to render everything inside my world border, and now Pl3x has rendered everything *new* but still not the old chunks. In my image below, the black area is old chunks. Any ideas on how I can force an update? 

<img width="640" alt="Weird-Pl3x" src="https://user-images.githubusercontent.com/7086027/130545381-e3ed64ac-feda-41d8-85a8-e2748a024eb8.png">

**Comment by BillyGalbreath** [comment]
Use a pregen plugin (like Chunky) or start your server with `--forceUpgrade` to force all the chunks to load up at least once and upgrade.

**Comment by jaknz** [comment]
Cool, thanks for that! I searched high and low and didn't come across the `--forceUpgrade` option. That's perfect.
