### ISSUE TITLE
Background render doesn't respect biome blending?

### ISSUE THREAD

**Issue by koutsie** [pl3xgaming/Pl3xMap#90]
Ok so while fiddling around with plugins that make changes to biomes (Mainly [Vivaldi](https://www.spigotmc.org/resources/vivaldi.85292/)) I noticed that Pl3xMap quite unsurprisingly doesn't apply biome blending when background rendering a chunk update. 

Chunks which don't have had any background renders yet(but have custom biome colors indicated by orange):
![image](https://user-images.githubusercontent.com/18449778/132378118-7b5d6282-7476-4c91-9895-1f992fa1e577.png)

Chunks which have had a background render or two happen (purple non-biome blended chunks):
![image](https://user-images.githubusercontent.com/18449778/132378129-146c4cf5-62f7-4c61-850f-58f29f198cb9.png)

**Comment by Ashparty** [comment]
> Ok so while fiddling around with plugins that make changes to biomes (Mainly [Vivaldi](https://www.spigotmc.org/resources/vivaldi.85292/)) I noticed that Pl3xMap quite unsurprisingly doesn't apply biome blending when background rendering a chunk update.
> 
> Chunks which don't have had any background renders yet(but have custom biome colors indicated by orange): ![image](https://user-images.githubusercontent.com/18449778/132378118-7b5d6282-7476-4c91-9895-1f992fa1e577.png)
> 
> Chunks which have had a background render or two happen (purple non-biome blended chunks): ![image](https://user-images.githubusercontent.com/18449778/132378129-146c4cf5-62f7-4c61-850f-58f29f198cb9.png)

Its an issue with thread count, change Max render threads for both backround render and normal render to 
 [Set max-render-threads: -1] 
 It fixed the issue for me

**Comment by koutsie** [comment]
Oh wow, will try.
