### ISSUE TITLE
Any way to re-render certain chunks

### ISSUE THREAD

**Issue by plexus** [pl3xgaming/Pl3xMap#91]
I'm generating large structures using code, but only bits of them are visible on the map.

Is there anything extra I should do to make Pl3xMap aware of these changes?

The changes are being done through the [XSeries API XBlock#setType](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XBlock.java#L234)

For example:

![2021-09-13_115709_Minecraft 1 17 1](https://user-images.githubusercontent.com/32212/133064687-0ad2b95f-2240-4121-8a9e-b58ff6b6a061.png)
![2021-09-12_190834_Minecraft 1 17 1](https://user-images.githubusercontent.com/32212/133064689-248497ca-9e4d-4af5-af4a-092a156f3fb2.png)

**Comment by BillyGalbreath** [comment]
```
I'm generating large structures using code
```
What code?
