### ISSUE TITLE
Memory leak on fullrender

### ISSUE THREAD

**Issue by TheHappyHopper** [pl3xgaming/Pl3xMap#93]
Here's what ive tried

Garbage collecter:
Aikars flags, custom flags, default flags

Ram allocation:
10gb, 16gb, 24gb

config: 
setting compression to 0.5, setting max render threads to 8

it seems unavoidable, during a fullrender pl3xmap causes a memory leak which ultimately crashes the server on large worlds
server version: purpur 1.17.1 1393
pl3xmap version: 1.0.0 beta 126

**Comment by theomega24** [comment]
send the crash log

**Comment by TheHappyHopper** [comment]
https://pastebin.com/FgjLf4Nk
its not a crash but more like a freeze

**Comment by prefislt** [comment]
I noticed that Pl3xMap uses a bigger chunk of memory even without rendering. [Flare memory profiler screenshot - about 9 minutes of runtime](https://prnt.sc/1t3nfdm)

**Comment by theomega24** [comment]
Screenshots don't help, we need real info

**Comment by prefislt** [comment]
What is "real info"?

**Comment by MWHunter** [comment]
The flare link itself

**Comment by prefislt** [comment]
> 
> 
> The flare link itself

[Here you go.](https://flare.airplane.gg/e869b581)

**Comment by MWHunter** [comment]
You have given 9 gigabytes to the server.  Pl3xmap has ALLOCATED 3 GB here.  All this memory has likely been reclaimed by garbage collection.  Even if none of this memory was reclaimed by garbage collection, your server still wouldn't run out. I personally have rendered a 40k by 40k world without any memory issues.

I would assume that you are running pterodactyl and set your XMS and XMX to the total memory that you have allocated to the server container, which is causing this issue.  A freeze is what pterodactyl does when the container is out of memory and the out of memory killer isn't on.

**Comment by prefislt** [comment]
I have 11GB RAM on pterodactyl (left ~2GB for headroom). I don't know if this is normal behaviour for a map plugin just looked a bit much compared to other plugins. Right now with few players maybe it's not a problem but if Pl3xMap is that hungry for RAM it can cause frequent GC and lag spikes with higher load. I can be totally wrong tho.

**Comment by Strahilchu** [comment]
It's so bad it crashes my server, when will this be fixed?

**Comment by theomega24** [comment]
Please stop posting on every issue you can find. Its spamming the tracker.

**Comment by BillyGalbreath** [comment]
There is no memory leak. Read [point 3 on this comment](https://github.com/pl3xgaming/Pl3xMap/issues/111#issuecomment-977191474) for an explanation.
